### ISSUE TITLE
Process a press on a "Enter" button

### ISSUE THREAD

**Issue by yarikleto** [yarikleto/Password-creator#12]
If a user click on the "Enter" button we need to handle it and call a `onClickEncryptBtn` method in the a `Controller` class

**Comment by distroaryan** [comment]
Would like to work on this. @yarikleto

**Comment by yarikleto** [comment]
You can try)

**Comment by yarikleto** [comment]
Completed https://github.com/yarikleto/Password-creator/commit/6427c2ea23419dc8a2155f5677c4c7548dd8e28a
