### ISSUE TITLE
Add styles for a copy button

### ISSUE THREAD

**Issue by yarikleto** [yarikleto/Password-creator#3]
The copy button doesn't have any handsome styles, need to fix it

**Comment by Shreelaxmi-M** [comment]
I want to work on this issue,can u assign me?

**Comment by harsh863** [comment]
@yarikleto , can i work on this?

**Comment by yarikleto** [comment]
@shree-create OK)

**Comment by yarikleto** [comment]
> I want to work on this issue, can u assign me?

@shree-create thanks for offering to help! If it won't be fixed, I'll assign you)

**Comment by yarikleto** [comment]
I fixed it
